# Nordic Circular Construction Project Context
# FabricAir Nordic Research Platform
# Last updated: 2025-12-16

project:
  name: "Nordic Circular Construction (NCC)"
  full_name: "Nordic Circular Construction"
  related_entity: "Nordic Circular Hotspot (NCH)"
  funding: "Nordic Innovation"

  owner:
    organization: "Natural State AS"
    coordinator: "Jan Thomas Odegard"
    email: "janthomas@naturalstate.no"

  description: |
    Collaborative project aimed at accelerating circular construction in the Nordic region.
    One of four parallel projects supported by Nordic Innovation in sustainable construction.

  objectives:
    primary: "Support 16 Nordic companies in scaling circular construction solutions in Nordic market"
    focus_areas:
      - "Develop market access and demand"
      - "Bridge supply and demand"
      - "Reduce information gaps and competence shortages"
      - "Harmonize regulations across borders"

  partner_companies: 16

# FabricAir-specific workstream
fabricair_workstream:
  company: "FabricAir"
  country: "Denmark"
  category: "Ventilation - poly"
  solution_type: "Technical solution"

  mission: |
    Map companies in Finland, Sweden, and Norway specializing in collection of
    used polyester fibers for recycling, with capacity to deliver high volume,
    high quality (mono) raw materials within FabricAir's quality standards.

# Geographic scope
scope:
  countries:
    - name: "Finland"
      status: "complete"
      completion: 95
      primary_recycler: "Rester"
      capacity: "6,000-12,000 t/yr"

    - name: "Sweden"
      status: "complete"
      completion: 92
      primary_recycler: "Rewin (2027)"
      capacity: "20,000 t/yr"

    - name: "Norway"
      status: "complete"
      completion: 88
      primary_recycler: "NTG"
      capacity: "30,000 t/yr"

  nordic_total:
    completion: 92
    combined_capacity: "56,000-62,000 t/yr"
    contacts_verified: 40+

# Deliverables
deliverables:
  primary:
    recipient: "FabricAir"
    format: "Web platform + PDF report"
    content:
      - "Answers to 6 research questions (Finland)"
      - "Country reports (Sweden, Norway)"
      - "Nordic comparison analysis"
      - "Top stakeholder list with verified contacts"
      - "Commercial phase roadmap"
      - "Contact directory"

  secondary:
    recipient: "NCC / Nordic Innovation"
    format: "Platform access + documentation"
    purpose: "Demonstrate methodology and outcomes"

# Delivery specifications
delivery:
  format:
    primary: "Web platform (optimized, designed)"
    secondary: "PDF report (following research question structure)"

  platform_requirements:
    - "Clean, professional design"
    - "Easy navigation"
    - "Scannable content"
    - "Quick-reference contacts"
    - "Responsive layout"
    - "Print-friendly"

  pdf_requirements:
    - "Executive summary"
    - "Research questions structure"
    - "Country analyses"
    - "Contact directory"
    - "Appendices"

  timeline:
    status: "Research complete"
    next_phase: "Platform design and PDF generation"

  post_delivery:
    - "Potential continued platform development"
    - "Partnership development support"
    - "Additional research as needed"

# Research structure interconnection
interconnection:
  description: |
    All project components are interconnected. Changes in one area
    propagate to related documents and data files.

  data_flow:
    research_questions: "Core framework - findings flow to all docs"
    sources: "Supports all claims in docs"
    fabricair: "Requirements filter all recommendations"
    project: "Scope defines boundaries"

  document_dependencies:
    index_md:
      depends_on: ["executive_summary", "country_reports", "contacts"]
      updates_trigger: "Any key finding change"

    executive_summary:
      depends_on: ["research_questions", "country_reports", "contacts"]
      updates_trigger: "Priority partner or recommendation change"

    nordic_comparison:
      depends_on: ["finland_q1_q6", "sweden_report", "norway_report"]
      updates_trigger: "Any country data change"

    country_reports:
      depends_on: ["verification_reports", "contacts"]
      updates_trigger: "Verification status or contact change"

    contact_directory:
      depends_on: ["all_verification_reports"]
      updates_trigger: "Any contact verification"

# Key findings (synchronized across all docs)
key_findings:
  strategic:
    - id: "KF-001"
      finding: "Rester is PRIMARY Finnish recycler"
      impact: "Critical partner identified"
      confidence: "high"
      affects: ["executive_summary", "nordic_comparison", "q6", "contacts"]

    - id: "KF-002"
      finding: "LSJH Turku plant CANCELLED (April 2024)"
      impact: "Strategy pivot - Rester now only option"
      confidence: "high"
      affects: ["executive_summary", "nordic_comparison", "q5", "q6"]

    - id: "KF-003"
      finding: "Rewin 20k t/yr chemical recycling by Oct 2027"
      impact: "Sweden domestic option coming"
      confidence: "high"
      affects: ["executive_summary", "nordic_comparison", "sweden_report"]

    - id: "KF-004"
      finding: "NTG 30k t/yr by ~2029"
      impact: "Largest Nordic capacity"
      confidence: "high"
      affects: ["executive_summary", "nordic_comparison", "norway_report"]

    - id: "KF-005"
      finding: "65/35 poly-cotton blends NOT suitable"
      impact: "Technical constraint - target cleanroom/pharma"
      confidence: "high"
      affects: ["q1", "fabricair_profile", "all_country_reports"]

    - id: "KF-006"
      finding: "Cleanroom/pharma = best 100% white PET source"
      impact: "Sector targeting recommendation"
      confidence: "high"
      affects: ["executive_summary", "q1", "q6", "all_country_reports"]

  market_data:
    finland:
      textile_waste: "85,770 t/yr"
      market_size: "€350-450M"
      recycling_rate: "<1%"
      source: "SYKE 2021"
      verified: true

    sweden:
      textile_waste: "60-80k t/yr"
      market_size: "€560M"
      recycling_rate: "<1%"
      source: "Naturvårdsverket"
      verified: true

    norway:
      textile_waste: "~100k t/yr"
      market_size: "€180-270M"
      recycling_rate: "<1%"
      source: "SSB"
      verified: true

# Priority partners (synchronized across contacts and docs)
priority_partners:
  tier_1_recyclers:
    - name: "Rester"
      country: "Finland"
      ceo: "Jukka Pesola (Aug 2025)"
      contact: "hello@rester.fi"
      capacity: "6k t/yr current, 12k target"
      status: "operational"
      risk: "Lindström is 2nd largest shareholder"

    - name: "NTG"
      country: "Norway"
      ceo: "Bent T. Mathisen"
      contact: "btm@ntgas.no"
      capacity: "2k t/yr current, 30k target by ~2029"
      status: "scaling"
      unique: "Can process poly-cotton blends via defibration"

    - name: "Rewin"
      country: "Sweden"
      contact: "via wargoninnovation.se"
      status: "launching_2027"

  tier_2_aggregators:
    - name: "Touchpoint"
      country: "Finland"
      contact: "noora.salonoja@touchpoint.fi"

    - name: "Puro"
      country: "Finland"
      contact: "paavo.martikainen@puro.fi"

    - name: "Nor Tekstil"
      country: "Norway"
      contact: "thomas.karlsen@nortekstil.no"

# Status tracking
status:
  last_updated: "2025-12-16"
  phase: "FabricAir Document Analysis - Technical Validation"
  overall_completion: 80
  delivery_grade: "B-"
  note: "Analyzing FabricAir internal docs to refine technical requirements and validate data relevance"

  milestones:
    - milestone: "Finland research"
      status: "complete"
      date: "2025-11-28"

    - milestone: "Sweden research"
      status: "complete"
      date: "2025-11-29"

    - milestone: "Norway research"
      status: "complete"
      date: "2025-11-29"

    - milestone: "Platform design overhaul"
      status: "complete"
      date: "2025-11-29"

    - milestone: "Backend synchronization"
      status: "complete"
      date: "2025-12-08"

    - milestone: "Project cleanup & verification"
      status: "complete"
      date: "2025-12-08"

    - milestone: "Build troubleshooting"
      status: "complete"
      date: "2025-12-16"

    - milestone: "Research context & prompts"
      status: "complete"
      date: "2025-12-16"

    - milestone: "FabricAir document analysis"
      status: "in_progress"
      date: "2025-12-16"

    - milestone: "Technical specification refinement"
      status: "pending"

    - milestone: "Quality assurance validation"
      status: "pending"

    - milestone: "Final platform optimization"
      status: "pending"

    - milestone: "PDF report generation"
      status: "pending"

    - milestone: "Delivery"
      status: "pending"
