# Sources Registry
# FabricAir Nordic Research Platform
# Last updated: 2025-12-16

# Source categories
categories:
  - id: "primary"
    name: "Primary Sources"
    description: "Direct communication, official company data, government statistics"
  - id: "secondary"
    name: "Secondary Sources"
    description: "Industry reports, research papers, news articles"
  - id: "tertiary"
    name: "Tertiary Sources"
    description: "Compilations, summaries, general reference"

# Verification states
verification_states:
  - state: "verified"
    description: "Content confirmed accurate through cross-reference or direct contact"
  - state: "verified_but_incompatible"
    description: "Source verified but material NOT compatible with FabricAir requirements"
  - state: "accessed"
    description: "Source accessed and content reviewed"
  - state: "referenced"
    description: "Referenced but not directly verified"
  - state: "outdated"
    description: "Information may need refresh (>2 years old)"

# ============================================
# FINLAND SOURCES
# ============================================

finland_sources:
  government_statistics:
    - id: "FI-GOV-001"
      name: "SYKE Material Flow Analysis 2021"
      type: "Government report"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "85,770 tonnes/year textile waste"
        - "60% incineration rate"
      used_in: ["q3", "executive_summary", "nordic_comparison"]

    - id: "FI-GOV-002"
      name: "Finnish Waste Act (Decree 978/2021)"
      type: "Legislation"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "Mandatory collection since Jan 2023"
      used_in: ["q4", "regulations"]

  company_sources:
    - id: "FI-COM-001"
      name: "Rester Oy"
      url: "https://rester.fi"
      type: "Company website"
      category: "primary"
      verification: "verified"
      key_data:
        - "6,000-12,000 t/yr capacity"
        - "GRS certified"
        - "€4.9M funding raised Jan 2025 (Tesi + others)"
        - "Strategy shift: high potential industrial applications"
      leadership:
        ceo: "Jukka Pesola (Aug 15, 2025)"
        previous_ceo: "Joachim Colliander (Feb 2024 - Aug 2025)"
        founder: "Outi Luukko (Board)"
        chair: "Hanna Liiri (investor profile, Feb 2024)"
        sales: "Johanna Lindholm-Järvinen"
        production: "Jani Tolvanen (acting)"
      contacts_verified: ["hello@rester.fi"]
      used_in: ["q5", "q6", "executive_summary"]
      last_verified: "2025-12-16"

    - id: "FI-COM-002"
      name: "Touchpoint Workwear"
      url: "https://www.touchpointww.com"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "Rester majority owner"
        - "ReTouch fabric"
      contacts_verified:
        - "noora.salonoja@touchpoint.fi"
        - "joni.maenpaa@touchpoint.fi"
      used_in: ["q5", "q6", "contacts"]

    - id: "FI-COM-003"
      name: "Lindström Group"
      url: "https://lindstromgroup.com"
      type: "Company website"
      category: "primary"
      verification: "verified_but_incompatible"
      last_verified: "2025-12-17"
      compatibility_status: "NOT_COMPATIBLE"
      critical_finding: |
        65% polyester / 35% cotton blend — NOT suitable for FabricAir 100% PET requirement.
        400 t/year output is incompatible. EXCLUDED from sourcing recommendations.
      key_data:
        - "50-70% market share"
        - "Rester 2nd largest shareholder (capacity lock risk)"
        - "Material: 65/35 poly-cotton blend (INCOMPATIBLE)"
      used_in: ["q1", "q2", "q6"]
      warning: "Do NOT pursue as feedstock source"

    - id: "FI-COM-004"
      name: "LSJH (Lounais-Suomen Jätehuolto)"
      url: "https://lsjh.fi"
      type: "Company website"
      category: "primary"
      verification: "verified"
      key_data:
        - "Turku 20k t/yr refinement plant ABANDONED"
        - "Outsourcing sorting to Turun Ekotori (2026)"
        - "LSJH stepping back from textile operations"
        - "Lemppari textile recycling store closing end 2025"
      status_change: "2025-10-07"
      status_note: |
        LSJH announced outsourcing textile sorting/QA to Turun Ekotori starting
        early 2026. LSJH will continue collection only in own area. This signals
        municipal collection model instability under evolving EU EPR rules.
      used_in: ["q5", "executive_summary"]
      last_verified: "2025-12-16"

    - id: "FI-COM-005"
      name: "Puro Tekstiilipalvelu"
      url: "https://puro.fi"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "45M items/year"
        - "HUS textiles"
      contacts_verified: ["paavo.martikainen@puro.fi"]
      used_in: ["q6", "contacts"]

  industry_sources:
    - id: "FI-IND-001"
      name: "Asiakastieto"
      type: "Business registry"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "€350-450M textile rental market"
      used_in: ["q1", "market_analysis"]

# ============================================
# SWEDEN SOURCES
# ============================================

sweden_sources:
  government_statistics:
    - id: "SE-GOV-001"
      name: "Naturvårdsverket (EPA)"
      url: "https://www.naturvardsverket.se"
      type: "Government agency"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "60-80k tonnes/year textile waste"
        - "EPR April 2028"
      used_in: ["sweden_report", "nordic_comparison"]

    - id: "SE-GOV-002"
      name: "Vinnova"
      url: "https://www.vinnova.se"
      type: "Innovation agency"
      category: "primary"
      verification: "accessed"
      last_verified: "2025-12-17"
      key_data:
        - "Rewin project funding"
      used_in: ["sweden_report"]

  company_sources:
    - id: "SE-COM-001"
      name: "Wargön Innovation / Rewin"
      url: "https://wargoninnovation.se"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "20,000 t/yr by October 2027"
        - "Chemical fiber-to-fiber"
      used_in: ["sweden_report", "executive_summary", "nordic_comparison"]

    - id: "SE-COM-002"
      name: "SIPTex / Sysav"
      url: "https://sysav.se"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "24,000 t/yr sorting capacity"
        - "NIR + visual spectroscopy"
      contacts_verified: ["lars.carrick@sysav.se"]
      used_in: ["sweden_report", "nordic_comparison"]

    - id: "SE-COM-003"
      name: "Elis Sweden"
      url: "https://se.elis.com"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      contacts_verified: ["patrik.nyholm@elis.com"]
      used_in: ["sweden_report", "contacts"]

  research_sources:
    - id: "SE-RES-001"
      name: "RE:Source / RISE"
      url: "https://resource-sip.se"
      type: "Research program"
      category: "primary"
      verification: "accessed"
      last_verified: "2025-12-17"
      used_in: ["sweden_report"]

    - id: "SE-RES-002"
      name: "Chalmers University"
      type: "Academic"
      category: "secondary"
      verification: "accessed"
      last_verified: "2025-12-17"
      key_data:
        - "Textile recycling research"
      used_in: ["sweden_report"]

# ============================================
# NORWAY SOURCES
# ============================================

norway_sources:
  government_statistics:
    - id: "NO-GOV-001"
      name: "SSB (Statistics Norway)"
      url: "https://www.ssb.no"
      type: "Government statistics"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "~100,000 tonnes/year textile waste"
      used_in: ["norway_report", "nordic_comparison"]

    - id: "NO-GOV-002"
      name: "Miljødirektoratet"
      type: "Environment agency"
      category: "primary"
      verification: "accessed"
      last_verified: "2025-12-17"
      key_data:
        - "EPR timeline under review"
      used_in: ["norway_report"]

  company_sources:
    - id: "NO-COM-001"
      name: "NTG (Norsk Tekstilgjenvinning)"
      url: "https://www.ntgas.no"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "30,000 t/yr target by ~2027"
        - "Patented defibration"
        - "Handles poly-cotton blends"
      contacts_verified: ["btm@ntgas.no"]
      used_in: ["norway_report", "executive_summary", "nordic_comparison"]

    - id: "NO-COM-002"
      name: "Nor Tekstil"
      url: "https://www.nortekstil.no"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "Largest Norwegian textile services"
        - "€118M revenue"
      contacts_verified: ["thomas.karlsen@nortekstil.no"]
      used_in: ["norway_report", "contacts"]

    - id: "NO-COM-003"
      name: "Fretex"
      url: "https://fretex.no"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "13,500 t/yr collection"
      contacts_verified: ["kristin.hareide@fretex.no"]
      used_in: ["norway_report", "contacts"]

    - id: "NO-COM-004"
      name: "Elis Norge"
      url: "https://no.elis.com"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      contacts_verified: ["marit.flinder@elis.com"]
      used_in: ["norway_report", "contacts"]

# ============================================
# ADDITIONAL FINLAND SOURCES (Consolidated from inline citations)
# ============================================

additional_finland_sources:
  research_sources:
    - id: "FI-RES-001"
      name: "Turku UAS Textile Flows Study"
      url: "https://www.tuas.fi/en/articles/463/textile-flows-finland-consumption-textiles-steady-amount-textile-waste-rise/"
      type: "Research"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "85,770 t/yr textile waste (2019)"
        - "~60% incinerated"
        - "18% exported"
        - "3.11 kg/capita Helsinki region"
      used_in: ["q3", "phase2_research", "nordic_comparison"]

    - id: "FI-RES-002"
      name: "EastCham Finland Waste Management"
      url: "https://www.eastcham.fi/finnishwastemanagement/municipal-solid-waste/recycling-and-recovery/textile/"
      type: "Research"
      category: "secondary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "1,330 t/yr hotel/restaurant/hospital textile waste"
        - "53,408 kg/yr Defence Forces uniforms"
      used_in: ["phase2_research"]

  investment_sources:
    - id: "FI-INV-001"
      name: "Tesi Investment Article - Rester"
      url: "https://tesi.fi/en/article/rester-article/"
      type: "Investment report"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "11,000 t/yr total plant capacity"
        - "6,000 t/yr Rester production line"
        - "€6M funding raised summer 2022"
        - "Lindström led investment round"
      used_in: ["q5", "q6", "phase2_research"]

  government_sources:
    - id: "FI-GOV-003"
      name: "HUS (Helsinki University Hospital)"
      url: "https://www.hus.fi"
      type: "Government/Healthcare"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "Largest public contracting entity"
        - "Merged with Puro (Jan 2021)"
      contacts_verified: ["logistiikka.asiakaspalvelu@hus.fi"]
      used_in: ["phase2_research", "contacts"]

  industry_sources:
    - id: "FI-IND-002"
      name: "Pharma Industry Finland (PIF)"
      url: "https://www.pif.fi/"
      type: "Industry association"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "~5,400 employees in Finnish pharma"
      used_in: ["phase2_research"]

    - id: "FI-IND-003"
      name: "Puhdaspalvelu Network"
      url: "https://puhdaspalvelu.fi/palveluverkosto/uudenmaan-sairaalapesula-oy/"
      type: "Industry network"
      category: "secondary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "250+ textile care professionals"
        - "ISO 14001:2004, SFS-EN 14065 certified"
      used_in: ["phase2_research"]

  media_sources:
    - id: "FI-MED-001"
      name: "Motiivilehti"
      url: "https://motiivilehti.fi/"
      type: "Media"
      category: "tertiary"
      verification: "accessed"
      last_verified: "2025-12-17"
      key_data:
        - "Finland's largest hospital laundry (Puro)"
      used_in: ["phase2_research"]

  company_sources:
    - id: "FI-COM-006"
      name: "Orion Corporation"
      url: "https://www.orion.fi"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "~3,700-4,000 employees"
        - "Major pharma cleanroom operator"
      used_in: ["phase2_research"]

    - id: "FI-COM-007"
      name: "Image Wear"
      url: "https://imagewear.fi/en"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "Finnish workwear manufacturer"
      used_in: ["phase2_research"]

    - id: "FI-COM-008"
      name: "Pure Waste"
      url: "https://purewaste.com/"
      type: "Company website"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "100% recycled textile materials"
      used_in: ["phase2_research"]

  organization_sources:
    - id: "FI-ORG-001"
      name: "Sitra - Finnish Innovation Fund"
      url: "https://www.sitra.fi/en/cases/rester-is-finlands-first-large-scale-textile-recycling-plant-we-want-to-revolutionise-the-raw-materials-of-textiles-in-industry/"
      type: "Organization"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "Rester profile and case study"
      used_in: ["phase2_research"]

    - id: "FI-ORG-002"
      name: "Business Finland"
      url: "https://www.businessfinland.fi/en/whats-new/cases/2025/pure-waste-making-the-world-better"
      type: "Government agency"
      category: "primary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "Pure Waste case study"
      used_in: ["phase2_research"]

# ============================================
# EU-LEVEL SOURCES
# ============================================

eu_sources:
  organization_sources:
    - id: "EU-ORG-001"
      name: "Zero Waste Europe"
      url: "https://zerowasteeurope.eu/"
      type: "NGO"
      category: "secondary"
      verification: "verified"
      last_verified: "2025-12-17"
      key_data:
        - "Finland textile policy context"
      used_in: ["phase2_research"]

# ============================================
# INTERNAL PROJECT SOURCES
# ============================================

internal_sources:
  finland_research:
    - id: "INT-FI-001"
      filename: "Finnish-Sectors-and-Actors-Using-High-Quality-Polyester-Workwear.md"
      maps_to: "Q1"
      status: "extracted"

    - id: "INT-FI-002"
      filename: "Main-Stakeholders-in-Finnish-High-Quality-Polyester-Textile-Production-Use-and-Reuse.md"
      maps_to: "Q2"
      status: "extracted"

    - id: "INT-FI-003"
      filename: "High-Quality-Polyester-Textile-Disposal-and-Reuse-in-Finland.md"
      maps_to: "Q3"
      status: "extracted"

    - id: "INT-FI-004"
      filename: "Regulations-on-Polyester-Textile-Disposal-and-Reuse-in-Finland.md"
      maps_to: "Q4"
      status: "extracted"

    - id: "INT-FI-005"
      filename: "Finnish-Polyester-Textile-Collection-and-Reuse-Initiatives.md"
      maps_to: "Q5"
      status: "extracted"

    - id: "INT-FI-006"
      filename: "Finnish-Stakeholders-for-High-Quality-Used-Polyester-Fiber-Sourcing.md"
      maps_to: "Q6"
      status: "extracted"

  verification_reports:
    - id: "VER-FI-P1"
      title: "Finland P1 Verification - Critical Claims"
      path: "docs/_internal/finland/P1-VERIFICATION-REPORT.md"
      status: "complete"

    - id: "VER-FI-P2"
      title: "Finland P2 Verification - Operations"
      path: "docs/_internal/finland/P2-VERIFICATION-REPORT.md"
      status: "complete"

    - id: "VER-FI-P3"
      title: "Finland P3 Verification - Strategy"
      path: "docs/_internal/finland/P3-VERIFICATION-REPORT.md"
      status: "complete"

    - id: "VER-SE-P1"
      title: "Sweden P1 Verification"
      path: "docs/_internal/sweden/SWEDEN-VERIFICATION-P1.md"
      status: "complete"

    - id: "VER-SE-P2"
      title: "Sweden P2 Verification"
      path: "docs/_internal/sweden/SWEDEN-VERIFICATION-P2.md"
      status: "complete"

    - id: "VER-SE-P3"
      title: "Sweden P3 Verification"
      path: "docs/_internal/sweden/SWEDEN-VERIFICATION-P3.md"
      status: "complete"

    - id: "VER-NO-P1"
      title: "Norway P1 Verification"
      path: "docs/_internal/norway/NORWAY-VERIFICATION-P1.md"
      status: "complete"

    - id: "VER-NO-P2P3"
      title: "Norway P2-P3 Verification"
      path: "docs/_internal/norway/NORWAY-VERIFICATION-P2-P3.md"
      status: "complete"

# ============================================
# SOURCE INTERCONNECTION
# ============================================

interconnection:
  description: |
    Sources are interconnected with documents through the 'used_in' field.
    When a source is updated, all dependent documents should be reviewed.

  propagation_rules:
    - trigger: "Source data changes"
      action: "Update all documents in 'used_in' list"

    - trigger: "Contact verification"
      action: "Update contacts_directory and relevant q6/country reports"

    - trigger: "New source added"
      action: "Add to registry and link to relevant documents"

# ============================================
# SOURCE QUALITY SUMMARY
# ============================================

quality_summary:
  last_updated: "2025-12-17"
  total_sources: 34
  verified: 28
  accessed: 6
  with_timestamps: 34
  by_country:
    finland: 21
    sweden: 7
    norway: 6
  by_category:
    primary: 28
    secondary: 4
    tertiary: 2
  consolidation_note: "Session 20: Consolidated 13 inline URLs from PHASE2-RESEARCH-FINDINGS.md into registry"
